BIST_50_SYMBOLS = [
    "AEFES", "AKBNK", "ALARK", "ARCLK", "ASELS", "ASTOR", "BIMAS", "BRSAN",
    "CCOLA", "CIMSA", "DOAS", "DOHOL", "EKGYO", "ENJSA", "ENKAI", "EREGL",
    "FROTO", "GARAN", "GUBRF", "HALKB", "HEKTS", "ISCTR", "KCHOL", "KONTR",
    "KOZAL", "KRDMD", "MAVI", "MGROS", "MIATK", "ODAS", "OYAKC", "PETKM",
    "PGSUS", "REEDR", "SAHOL", "SASA", "SISE", "SOKM", "TAVHL", "TCELL",
    "THYAO", "TKFEN", "TOASO", "TTKOM", "TUPRS", "ULKER", "VAKBN", "VESTL",
    "YKBNK", "ZOREN"
]